# Data Encoding 

In [ ]:
# 1. Normal Encoding
# 2. Lebel and ordinal
# 3. Target guided and ordinal encoding.

In [ ]:
# data encoding >> Converting categorical columns into numeric

# Nominal encoding 

In [1]:
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder

In [5]:
df= pd.DataFrame({'status': ['single','married', 'separated', 'single', 'single', 'married', 'married']})

In [6]:
df

status
0     single
1    married
2  separated
3     single
4     single
5    married
6    married

In [7]:
encoder = OneHotEncoder()

In [8]:
encoder

OneHotEncoder()

In [17]:
encoded = encoder.fit_transform(df[['status']]).toarray()

In [16]:
encoder.get_feature_names_out()

array(['status_married', 'status_separated', 'status_single'],
      dtype=object)

In [19]:
encoder_df = pd.DataFrame(encoded, columns = encoder.get_feature_names_out())

In [20]:
encoder_df

status_married  status_separated  status_single
0             0.0               0.0            1.0
1             1.0               0.0            0.0
2             0.0               1.0            0.0
3             0.0               0.0            1.0
4             0.0               0.0            1.0
5             1.0               0.0            0.0
6             1.0               0.0            0.0

In [21]:
# New data 
encoder.transform([['single']]).toarray()

C:\Users\SqyUser\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

In [22]:
df

status
0     single
1    married
2  separated
3     single
4     single
5    married
6    married

In [24]:
encoder_df

status_married  status_separated  status_single
0             0.0               0.0            1.0
1             1.0               0.0            0.0
2             0.0               1.0            0.0
3             0.0               0.0            1.0
4             0.0               0.0            1.0
5             1.0               0.0            0.0
6             1.0               0.0            0.0

In [25]:
pd.concat([df,encoder_df], axis=1)

status  status_married  status_separated  status_single
0     single             0.0               0.0            1.0
1    married             1.0               0.0            0.0
2  separated             0.0               1.0            0.0
3     single             0.0               0.0            1.0
4     single             0.0               0.0            1.0
5    married             1.0               0.0            0.0
6    married             1.0               0.0            0.0

In [27]:
import seaborn as sns 
sns.load_dataset('tips')

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

# Lebel Encoding >> assigns unique lebel to the categorical 

In [28]:
df

status
0     single
1    married
2  separated
3     single
4     single
5    married
6    married

In [34]:
from sklearn.preprocessing import LabelEncoder

In [38]:
label_encoder = LabelEncoder()

In [40]:
label_encoder.fit_transform(df[['status']])

C:\Users\SqyUser\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 2, 2, 0, 0])

In [41]:
label_encoder.transform([['single']])

C:\Users\SqyUser\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

In [42]:
label_encoder.transform([['married']])

C:\Users\SqyUser\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([0])

In [43]:
label_encoder.transform([['separated']])

C:\Users\SqyUser\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([1])

# ordinal encoding 

In [44]:
from sklearn.preprocessing import OrdinalEncoder

In [54]:
df = pd.DataFrame({'qualification': ['HS', 'GR', 'PG', 'PHD', 'HS', 'PHD', 'PG']})

In [55]:
df

qualification
0            HS
1            GR
2            PG
3           PHD
4            HS
5           PHD
6            PG

In [56]:
encoder = OrdinalEncoder(categories=[['HS', 'GR', 'PG', 'PHD', 'HS', 'PHD', 'PG']])

In [59]:
encoder

OrdinalEncoder(categories=[['HS', 'GR', 'PG', 'PHD', 'HS', 'PHD', 'PG']])

In [61]:
encoder.fit_transform(df[['qualification']])

array([[4.],
       [1.],
       [6.],
       [5.],
       [4.],
       [5.],
       [6.]])

In [63]:
# new data
encoder.transform([['PHD']])

C:\Users\SqyUser\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[5.]])

# Target guided Ordinal Encoding 

In [65]:
# relationship with target variable.
# A lot of unique categories. 
# replace the category with the mean and median of respective group target.

In [72]:
df = pd.DataFrame({
    'time': ['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner'],
    'total_bill': [120, 130, 90, 120, 130, 90, 160, 180, 189]
})

In [73]:
df

time  total_bill
0      lunch         120
1  breakfast         130
2     dinner          90
3      lunch         120
4  breakfast         130
5     dinner          90
6      lunch         160
7  breakfast         180
8     dinner         189

In [75]:
mean_price = df.groupby('time')['total_bill'].mean().to_dict()

In [76]:
mean_price

{'breakfast': 146.66666666666666, 'dinner': 123.0, 'lunch': 133.33333333333334}

In [78]:
df['time_encoded'] = df['time'].map(mean_price)

In [79]:
df

time  total_bill  time_encoded
0      lunch         120    133.333333
1  breakfast         130    146.666667
2     dinner          90    123.000000
3      lunch         120    133.333333
4  breakfast         130    146.666667
5     dinner          90    123.000000
6      lunch         160    133.333333
7  breakfast         180    146.666667
8     dinner         189    123.000000

In [80]:
encoder = OrdinalEncoder(categories=[['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch','breakfast']])

In [81]:
encoder

OrdinalEncoder(categories=[['lunch', 'breakfast', 'dinner', 'lunch',
                            'breakfast', 'dinner', 'lunch', 'breakfast']])

In [82]:
encoder.fit_transform(df[['time']])

array([[6.],
       [7.],
       [5.],
       [6.],
       [7.],
       [5.],
       [6.],
       [7.],
       [5.]])

In [83]:
encoder.transform([['dinner']])

C:\Users\SqyUser\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[5.]])

In [84]:
encoder.transform([['breakfast']])

C:\Users\SqyUser\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[7.]])