In [1]:
import numpy as np


In [9]:
arr = np.random.randint(1,10,(4,4))

In [10]:
arr

array([[2, 7, 9, 7],
       [2, 6, 7, 2],
       [9, 4, 9, 3],
       [9, 3, 3, 7]])

In [11]:
arr.reshape(8,2)

array([[2, 7],
       [9, 7],
       [2, 6],
       [7, 2],
       [9, 4],
       [9, 3],
       [9, 3],
       [3, 7]])

In [12]:
arr

array([[2, 7, 9, 7],
       [2, 6, 7, 2],
       [9, 4, 9, 3],
       [9, 3, 3, 7]])

In [13]:
arr.T 

array([[2, 2, 9, 9],
       [7, 6, 4, 3],
       [9, 7, 9, 3],
       [7, 2, 3, 7]])

In [14]:
arr.flatten()

array([2, 7, 9, 7, 2, 6, 7, 2, 9, 4, 9, 3, 9, 3, 3, 7])

In [15]:
np.expand_dims(arr,axis=1)

array([[[2, 7, 9, 7]],

       [[2, 6, 7, 2]],

       [[9, 4, 9, 3]],

       [[9, 3, 3, 7]]])

In [16]:
np.expand_dims(arr,axis=0)

array([[[2, 7, 9, 7],
        [2, 6, 7, 2],
        [9, 4, 9, 3],
        [9, 3, 3, 7]]])

In [20]:
data = np.array([[1],[2],[3]])

In [21]:
np.squeeze(data)

array([1, 2, 3])

In [22]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [23]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [24]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [25]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [29]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#Numpy - Binary Operators.

In [33]:
arr1 = np.random.randint(1,10,(3,4))

In [34]:
arr2 = np.random.randint(1,10,(3,4))

In [35]:
arr1

array([[9, 5, 9, 2],
       [2, 4, 2, 5],
       [1, 5, 8, 7]])

In [36]:
arr2

array([[9, 5, 3, 9],
       [8, 6, 6, 2],
       [3, 8, 4, 5]])

In [37]:
arr1+arr2

array([[18, 10, 12, 11],
       [10, 10,  8,  7],
       [ 4, 13, 12, 12]])

In [38]:
arr1*arr2

array([[81, 25, 27, 18],
       [16, 24, 12, 10],
       [ 3, 40, 32, 35]])

In [39]:
arr2-arr1

array([[ 0,  0, -6,  7],
       [ 6,  2,  4, -3],
       [ 2,  3, -4, -2]])

In [40]:
arr1**arr2

array([[387420489,      3125,       729,       512],
       [      256,      4096,        64,        25],
       [        1,    390625,      4096,     16807]])

In [41]:
arr1

array([[9, 5, 9, 2],
       [2, 4, 2, 5],
       [1, 5, 8, 7]])

In [42]:
arr1>arr2

array([[False, False,  True, False],
       [False, False, False,  True],
       [False, False,  True,  True]])

In [ ]:
#numpy- Sting Functions


In [44]:
arr = np.array(["sudh", "Kumar"])

In [45]:
arr

array(['sudh', 'Kumar'], dtype='<U5')

In [46]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [47]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [48]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [ ]:
#Numpy - Mathematical Functions.

In [49]:
arr1

array([[9, 5, 9, 2],
       [2, 4, 2, 5],
       [1, 5, 8, 7]])

In [50]:
np.sin(arr1)

array([[ 0.41211849, -0.95892427,  0.41211849,  0.90929743],
       [ 0.90929743, -0.7568025 ,  0.90929743, -0.95892427],
       [ 0.84147098, -0.95892427,  0.98935825,  0.6569866 ]])

In [53]:
np.cos(arr1)

array([[-0.91113026,  0.28366219, -0.91113026, -0.41614684],
       [-0.41614684, -0.65364362, -0.41614684,  0.28366219],
       [ 0.54030231,  0.28366219, -0.14550003,  0.75390225]])

In [54]:
np.tan(arr1)

array([[-0.45231566, -3.38051501, -0.45231566, -2.18503986],
       [-2.18503986,  1.15782128, -2.18503986, -3.38051501],
       [ 1.55740772, -3.38051501, -6.79971146,  0.87144798]])

In [55]:
np.log10(arr1)

array([[0.95424251, 0.69897   , 0.95424251, 0.30103   ],
       [0.30103   , 0.60205999, 0.30103   , 0.69897   ],
       [0.        , 0.69897   , 0.90308999, 0.84509804]])

In [56]:
np.exp(arr1)

array([[8.10308393e+03, 1.48413159e+02, 8.10308393e+03, 7.38905610e+00],
       [7.38905610e+00, 5.45981500e+01, 7.38905610e+00, 1.48413159e+02],
       [2.71828183e+00, 1.48413159e+02, 2.98095799e+03, 1.09663316e+03]])

In [57]:
np.power(arr1,2)

array([[81, 25, 81,  4],
       [ 4, 16,  4, 25],
       [ 1, 25, 64, 49]], dtype=int32)

In [58]:
np.mean(arr1)

4.916666666666667

In [59]:
np.median(arr1)

5.0

In [61]:
np.std(arr1)

2.722080495176846

In [62]:
np.var(arr1)

7.409722222222221

In [63]:
np.min(arr1)

1

In [64]:
np.max(arr1)

9

In [65]:
#Numpy - Airthmatic Operations 

In [66]:
arr1

array([[9, 5, 9, 2],
       [2, 4, 2, 5],
       [1, 5, 8, 7]])

In [67]:
arr2

array([[9, 5, 3, 9],
       [8, 6, 6, 2],
       [3, 8, 4, 5]])

In [68]:
arr1-arr2

array([[ 0,  0,  6, -7],
       [-6, -2, -4,  3],
       [-2, -3,  4,  2]])

In [69]:
np.subtract(arr1,arr2)

array([[ 0,  0,  6, -7],
       [-6, -2, -4,  3],
       [-2, -3,  4,  2]])

In [70]:
np.multiply(arr1,arr2)

array([[81, 25, 27, 18],
       [16, 24, 12, 10],
       [ 3, 40, 32, 35]])

In [71]:
np.mod(arr1,arr2)

array([[0, 0, 0, 2],
       [2, 4, 2, 1],
       [1, 5, 0, 2]])

In [72]:
np.power(arr1,arr2)

array([[387420489,      3125,       729,       512],
       [      256,      4096,        64,        25],
       [        1,    390625,      4096,     16807]])

In [74]:
np.sqrt(arr1)

array([[3.        , 2.23606798, 3.        , 1.41421356],
       [1.41421356, 2.        , 1.41421356, 2.23606798],
       [1.        , 2.23606798, 2.82842712, 2.64575131]])

In [75]:
np.sqrt(arr2)

array([[3.        , 2.23606798, 1.73205081, 3.        ],
       [2.82842712, 2.44948974, 2.44948974, 1.41421356],
       [1.73205081, 2.82842712, 2.        , 2.23606798]])

In [76]:
np.mean(arr1)

4.916666666666667