In [1]:
import numpy as np

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(0.5,10.5 ))

In [9]:
np.arange(.5,10.4)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [10]:
np.arange(.5,10.4, 0.2)

array([ 0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,  2.3,  2.5,
        2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,  4.5,  4.7,
        4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,  6.7,  6.9,
        7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,  8.9,  9.1,
        9.3,  9.5,  9.7,  9.9, 10.1, 10.3])

In [11]:
list(np.arange(.5,10.4, 0.2))

[0.5,
 0.7,
 0.8999999999999999,
 1.0999999999999999,
 1.2999999999999998,
 1.4999999999999998,
 1.6999999999999997,
 1.8999999999999997,
 2.0999999999999996,
 2.3,
 2.4999999999999996,
 2.6999999999999993,
 2.8999999999999995,
 3.0999999999999996,
 3.2999999999999994,
 3.499999999999999,
 3.6999999999999993,
 3.8999999999999995,
 4.1,
 4.299999999999999,
 4.499999999999999,
 4.699999999999999,
 4.899999999999999,
 5.099999999999999,
 5.299999999999999,
 5.499999999999999,
 5.699999999999999,
 5.899999999999999,
 6.099999999999999,
 6.299999999999999,
 6.499999999999998,
 6.699999999999998,
 6.899999999999999,
 7.099999999999999,
 7.299999999999999,
 7.499999999999998,
 7.699999999999998,
 7.899999999999999,
 8.099999999999998,
 8.299999999999997,
 8.499999999999998,
 8.699999999999998,
 8.899999999999999,
 9.099999999999998,
 9.299999999999997,
 9.499999999999998,
 9.699999999999998,
 9.899999999999999,
 10.099999999999998,
 10.299999999999997]

In [13]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [14]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [15]:
np.logspace(1,5,10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [19]:
np.zeros((3,4,2,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [20]:
np.ones(1)

array([1.])

In [22]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
arr+5

10

In [29]:
arr=np.ones((3,4))

In [30]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [32]:
arr*6

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [33]:
np.empty((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
arr1= np.eye(5)

In [36]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
import pandas as pd

In [45]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [46]:
np.random.rand(2,3)

array([[0.35513935, 0.53196591, 0.66233936],
       [0.46489377, 0.09182089, 0.1530025 ]])

In [47]:
np.random.randn(2,3)

array([[-2.20309336,  2.17446713, -0.5141451 ],
       [ 0.09335955,  1.10359473, -0.40353916]])

In [48]:
np.random.randint(1,5,(3,4))

array([[2, 4, 2, 3],
       [1, 4, 3, 2],
       [3, 3, 4, 1]])

In [50]:
arr2=np.random.randint(1,5,(3,4))

In [51]:
arr2

array([[2, 1, 2, 1],
       [4, 3, 4, 3],
       [1, 4, 1, 2]])

In [52]:
arr2.size

12

In [53]:
arr2.shape

(3, 4)

In [54]:
arr2.reshape(6,2)

array([[2, 1],
       [2, 1],
       [4, 3],
       [4, 3],
       [1, 4],
       [1, 2]])

In [55]:
arr2.reshape(4,3)

array([[2, 1, 2],
       [1, 4, 3],
       [4, 3, 1],
       [4, 1, 2]])

In [58]:
arr2.reshape(4,-1)

array([[2, 1, 2],
       [1, 4, 3],
       [4, 3, 1],
       [4, 1, 2]])

In [59]:
arr2.reshape(4,-1535427262)

array([[2, 1, 2],
       [1, 4, 3],
       [4, 3, 1],
       [4, 1, 2]])

In [60]:
arr2.reshape(2,2,3)

array([[[2, 1, 2],
        [1, 4, 3]],

       [[4, 3, 1],
        [4, 1, 2]]])

In [61]:
arr2.reshape(2,2,3,1,1,1,1,1)

array([[[[[[[[2]]]]],




         [[[[[1]]]]],




         [[[[[2]]]]]],





        [[[[[[1]]]]],




         [[[[[4]]]]],




         [[[[[3]]]]]]],






       [[[[[[[4]]]]],




         [[[[[3]]]]],




         [[[[[1]]]]]],





        [[[[[[4]]]]],




         [[[[[1]]]]],




         [[[[[2]]]]]]]])

In [63]:
arr1 = np.random.randint(1,10,(5,6))

In [64]:
arr1

array([[3, 7, 2, 4, 7, 9],
       [2, 1, 6, 5, 1, 4],
       [9, 4, 9, 7, 9, 6],
       [1, 8, 7, 7, 4, 7],
       [3, 3, 6, 5, 2, 3]])

In [65]:
arr1>8

array([[False, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [ True, False,  True, False,  True, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [66]:
arr1[arr1>8]

array([9, 9, 9, 9])

In [67]:
arr1

array([[3, 7, 2, 4, 7, 9],
       [2, 1, 6, 5, 1, 4],
       [9, 4, 9, 7, 9, 6],
       [1, 8, 7, 7, 4, 7],
       [3, 3, 6, 5, 2, 3]])

In [68]:
arr1[0]

array([3, 7, 2, 4, 7, 9])

In [69]:
arr1[0,[0,1]]

array([3, 7])

In [73]:
arr1[2:4,[3,4]]

array([[7, 9],
       [7, 4]])

In [93]:
arr1 = np.random.randint(1,3,(3,2))
arr2 = np.random.randint(1,3,(3,2))

In [109]:
arr1

array([[2],
       [2]])

In [110]:
arr2

array([[2, 1, 2, 1],
       [4, 3, 4, 3],
       [1, 4, 1, 2]])

###we can multiply, addition, substract and divide both of arrays###

In [113]:
arr = np.zeros((3,4))

In [114]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [115]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [116]:
a = np.array([1,2,3,4])

In [117]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [126]:
b = np.array([[3,4,5]])

In [127]:
arr+b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [128]:
b.T

array([[3],
       [4],
       [5]])

In [129]:
arr1 = b.T

In [130]:
arr1

array([[3],
       [4],
       [5]])

In [131]:
np.sqrt(arr1)

array([[1.73205081],
       [2.        ],
       [2.23606798]])

In [132]:
np.log10(arr1)

array([[0.47712125],
       [0.60205999],
       [0.69897   ]])

In [133]:
np.exp(arr1)

array([[ 20.08553692],
       [ 54.59815003],
       [148.4131591 ]])

In [134]:
np.mean(arr1)

4.0

In [136]:
np.max(arr1)

5