In [1]:
import numpy as np

In [2]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [14]:
arr = np.array([26,35,14,5,61,98,54,23])

In [12]:
arr

array([2, 3, 4, 5, 6])

In [19]:
np.sort(arr)

array([ 5, 14, 23, 26, 35, 54, 61, 98])

In [23]:
np.searchsorted(arr,3)

0

In [24]:
arr1 = np.array([0,324,765,76,98,5,0,0,0,234])

In [25]:
np.count_nonzero(arr1)

6

In [26]:
np.where(arr1>0)

(array([1, 2, 3, 4, 5, 9], dtype=int64),)

In [32]:
np.extract(arr1>2,arr1)

array([324, 765,  76,  98,   5, 234])

In [ ]:
#Numpy - Byte swapping

In [33]:
arr1

array([  0, 324, 765,  76,  98,   5,   0,   0,   0, 234])

In [37]:
arr.byteswap(True)

array([ 436207616,  587202560,  234881024,   83886080, 1023410176,
       1644167168,  905969664,  385875968])

In [38]:
arr

array([ 436207616,  587202560,  234881024,   83886080, 1023410176,
       1644167168,  905969664,  385875968])

In [39]:
arr

array([ 436207616,  587202560,  234881024,   83886080, 1023410176,
       1644167168,  905969664,  385875968])

In [ ]:
#numpy - Copies & Views

In [40]:
arr 

array([ 436207616,  587202560,  234881024,   83886080, 1023410176,
       1644167168,  905969664,  385875968])

In [41]:
a = np.copy(arr1)

In [43]:
b = arr1.view()

In [47]:
b

array([234, 324, 765,  76,  98,   5,   0,   0,   0, 234])

In [49]:
b[0]= 234

In [50]:
b

array([234, 324, 765,  76,  98,   5,   0,   0,   0, 234])

In [51]:
arr1

array([234, 324, 765,  76,  98,   5,   0,   0,   0, 234])

In [ ]:
#Numpy - Matrix Library.

In [52]:
import numpy.matlib as nm

In [53]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [54]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [55]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
#Numpy - Linear Algebra

In [56]:
arr1

array([234, 324, 765,  76,  98,   5,   0,   0,   0, 234])

In [62]:
arr1 = np.random.randint([[2,3],[4,5]])

In [61]:
arr2 = np.random.randint([[5,3],[2,5]])

In [63]:
arr1

array([[1, 1],
       [0, 1]])

In [64]:
arr2

array([[1, 0],
       [1, 4]])

In [65]:
np.dot(arr1,arr2)

array([[2, 4],
       [1, 4]])

In [66]:
arr1@arr2

array([[2, 4],
       [1, 4]])